---
version: "2.0"

services:
  web:
    image: zjor/qr-share:latest
    expose:
      - port: 5000
        as: 80
        to:
          - global: true
    env:
      - PORT=5000
      - REGION=us-east-1
      - S3_API_KEY=A202A91780C3CBA5BFE8
      - S3_SECRET=Yv0WhMjVSX02jmXH2oNw0oLA6JLHFqeIuAGavt1h
      - S3_ENDPOINT=https://s3.filebase.com

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    akash:
      attributes:
        host: nixaid
      pricing:
        web: 
          denom: uakt
          amount: 1000

deployment:
  web:
    akash:
      profile: web
      count: 1
